### ISSUE TITLE
documentation: clearly link ref code to benchmark tasks

### ISSUE THREAD

**Issue by martinjaggi** [mlbench/mlbench-benchmarks#14]
document the code (and task documentation) better that it's easy to navigate from benchmark task to the reference implementation of each task, and the other way around.

https://github.com/mlbench/mlbench-benchmarks/blob/develop/pytorch/linearmodels/openmpi-epsilon-logistic-regression-all-reduce/main.py

**Comment by Panaetius** [comment]
I've added references to all the benchmark tasks in the code of the implementations in https://github.com/mlbench/mlbench-benchmarks/commit/10ed26fea953989668d1951f28622638b48814fc

We currently have https://mlbench.readthedocs.io/projects/mlbench_benchmarks/en/latest/readme.html#benchmark-implementations to talk about implementation details of the implementations. The state of the documentation for this is not that great at the moment, since that task description at https://mlbench.readthedocs.io/en/latest/benchmark-tasks.html#a-image-classification-resnet-cifar-10 contain a lot of implementation details that are not part of the task itself. At least I think things like batch size are implementation details and not part of a task itself. That really depends on how exactly we delineate Tasks from Implementations, which has been fuzzy so far.

The reason I bring this up is that it would be nice to have a Readme.rst in each implementation folder that documents the implementation and links back to the task it implements. That readme can be included automatically in the benchmark docs at https://mlbench.readthedocs.io/projects/mlbench_benchmarks/en/latest/readme.html discussing implementation details, which in turn are linked to from the task descriptions here https://mlbench.readthedocs.io/en/latest/benchmark-tasks.html

But for this to make any sense and not be confusing, Task and Implementation documentation have to be clearly separated.

**Comment by martinjaggi** [comment]
very good, let's do this

**Comment by Panaetius** [comment]
I added first rudimentary Readme.rst's in https://github.com/mlbench/mlbench-benchmarks/commit/343fcb4ddc4ed07b513d1d55aab5038fafd3c9ff and linked them to the generated docs.

How do we split Task & Implementation? I.e. What is still part of a Task and what is Implementation specific?

**Comment by martinjaggi** [comment]
looks good.

about the split, the idea is that the result metrics (the official ones) need to be reproducible from the task description alone. so the parameters described there will basically stay, but the task needs to be implementable say both in pytorch and TF .... the rest can be in implementation (things like random seed etc are there, even if they have slight influence on results. hopefully only very little).
